### ISSUE TITLE
显示模糊

### ISSUE THREAD

**Issue by SanceTb** [Gelinzh/Atoz#1]
在以下两台电脑中出现了显示模糊的情况：

分辨率3840x2160，缩放比例150%
Windows 10 Pro 2020H2 Beta，JRE 14.0.1

分辨率2256x1504，缩放比例150%
Windows 10 Home 2004，无JRE

在第二台电脑中将缩放比例改为100%后显示正常。

**Comment by SanceTb** [comment]
屏幕缩放比例不为100%的情况在笔记本和高分屏中均非常常见。
本软件目标受众是四六级考生，而四六级考生中使用笔记本的应该是大多数，故而对这种情况做适配应该能给很多人带来方便

**Comment by acelych** [comment]
我自己试了试，的确有这个问题，改150%缩放的时候像素点三步并作两步走自然会模糊
暂时找不到好的办法，貌似是swing的通病，网上找了一圈都是在说C#怎么获取系统缩放比例的
建议125%缩放吧，125%缩放不会改变实际dpi
